/* countries.js — HopeScholar | REST Countries API */
'use strict';
const EXCLUDED=['British Indian Ocean Territory','French Southern Territories','Saint Helena, Ascension and Tristan da Cunha','Mayotte','Reunion','Western Sahara'];
const Countries={data:[],loaded:false,
async load(){if(this.loaded){this.render();return;}clearError('country');showLoader('country');const cached=Cache.get('african_countries');if(cached){this.data=cached;this.loaded=true;hideLoader('country');this.render();showToast('Loaded from cache ⚡');return;}try{const res=await fetchWithTimeout('https://restcountries.com/v3.1/region/africa?fields=name,flags,capital,population,subregion,cca2');const json=await res.json();if(!Array.isArray(json))throw new Error('Unexpected API response.');const filtered=json.filter(c=>!EXCLUDED.includes(c.name.common)).sort((a,b)=>a.name.common.localeCompare(b.name.common));Cache.set('african_countries',filtered);this.data=filtered;this.loaded=true;hideLoader('country');this.render();}catch(e){hideLoader('country');showError('country',`Could not load countries: ${e.message}`);}},
render(){const grid=$('country-grid');const search=validateInput($('country-search').value).toLowerCase();const region=$('country-region').value;const sort=$('country-sort').value;let list=[...this.data];if(search)list=list.filter(c=>c.name.common.toLowerCase().includes(search)||(c.capital?.[0]??'').toLowerCase().includes(search));if(region)list=list.filter(c=>c.subregion===region);if(sort==='name-asc')list.sort((a,b)=>a.name.common.localeCompare(b.name.common));if(sort==='pop-desc')list.sort((a,b)=>b.population-a.population);if(sort==='pop-asc')list.sort((a,b)=>a.population-b.population);showStats('country',`${list.length} countr${list.length!==1?'ies':'y'} shown`);if(!list.length){grid.innerHTML=emptyStateHtml('🌍','No countries found','Adjust your search or region filter.');return;}grid.innerHTML=list.map(c=>this._cardHtml(c)).join('');},
_cardHtml(c){const cap=c.capital?.[0]??'N/A';const flagHtml=c.flags?.png?`<img class="country-flag" src="${escapeHtml(c.flags.png)}" alt="Flag of ${escapeHtml(c.name.common)}" loading="lazy" width="62" height="42"/>`:`<span style="font-size:2rem">🏳️</span>`;return`<article class="country-card" role="listitem" onclick="Countries._onClick('${escapeHtml(c.name.common).replace(/'/g,"\\'")}')" tabindex="0" aria-label="${escapeHtml(c.name.common)}" onkeydown="if(event.key==='Enter')Countries._onClick('${escapeHtml(c.name.common).replace(/'/g,"\\'")}')"> ${flagHtml}<h3 class="country-name">${escapeHtml(c.name.common)}</h3><p class="country-capital">🏛 ${escapeHtml(cap)}</p><p class="country-pop">👥 ${formatNumber(c.population)}</p>${c.subregion?`<span class="tag tag-gold" style="width:fit-content">${escapeHtml(c.subregion)}</span>`:''}<p class="country-cta">🎓 Find universities ${ARROW_SVG}</p></article>`;},
_onClick(name){switchTab('universities');window._closeSidebar?.();const sel=$('uni-country');let opt=Array.from(sel.options).find(o=>o.value.toLowerCase()===name.toLowerCase());if(!opt){opt=new Option(name,name);sel.appendChild(opt);}sel.value=opt.value;Universities.data=[];Universities.loaded=false;Universities.load();}};
document.addEventListener('DOMContentLoaded',()=>{$('country-search')?.addEventListener('input',debounce(()=>{if(Countries.loaded)Countries.render();},250));$('country-region')?.addEventListener('change',()=>{if(Countries.loaded)Countries.render();});$('country-sort')?.addEventListener('change',()=>{if(Countries.loaded)Countries.render();});});
