/* ══════════════════════════════════════════════════════════════
   data.js — Curated scholarship & university data
   Sources: Mastercard Foundation Scholars Program,
            Fully Funded / Work Colleges, Global Scholarships
   Author: Gabriel Mugisha | ALU | gabrielmugisha.tech
   Project: HopeScholar
   ══════════════════════════════════════════════════════════════ */

'use strict';

const SCHOLARSHIPS = [

  // ════════════════════════════════════════════════════════════
  // MASTERCARD FOUNDATION — AFRICA
  // ════════════════════════════════════════════════════════════
  {
    id: 1,
    name: 'African Leadership University (ALU)',
    country: 'Rwanda / Mauritius', flag: '🇷🇼', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Social Impact, Entrepreneurship, Software Engineering',
    description: 'Mastercard Foundation Scholars Program partner. Innovative competency-based education developing ethical, entrepreneurial African leaders.',
    link: 'https://www.alueducation.com',
    tags: ['Mastercard', 'Leadership', 'Software Engineering', 'Entrepreneurship'],
  },
  {
    id: 2,
    name: 'African Leadership Academy',
    country: 'South Africa', flag: '🇿🇦', region: 'africa',
    category: 'mastercard', level: 'Pre-University / Undergraduate', window: 'check',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Entrepreneurship, Community Projects',
    description: 'Mastercard Foundation partner. Two-year pre-university program in South Africa developing Africa\'s next generation of leaders.',
    link: 'https://www.africanleadershipacademy.org',
    tags: ['Mastercard', 'Leadership', 'Entrepreneurship', 'Pre-University'],
  },
  {
    id: 3,
    name: 'Ashesi University',
    country: 'Ghana', flag: '🇬🇭', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Leadership, Business, Social Impact',
    description: 'Mastercard Foundation partner. Liberal arts and engineering university focused on ethical leadership and social impact in Ghana.',
    link: 'https://www.ashesi.edu.gh',
    tags: ['Mastercard', 'Computer Science', 'Business', 'Leadership'],
  },
  {
    id: 4,
    name: 'KNUST',
    country: 'Ghana', flag: '🇬🇭', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Engineering, Science, Technology, Leadership',
    description: 'Kwame Nkrumah University of Science and Technology. Mastercard partner — premier STEM university in West Africa.',
    link: 'https://www.knust.edu.gh',
    tags: ['Mastercard', 'Engineering', 'STEM', 'Technology'],
  },
  {
    id: 5,
    name: 'Makerere University',
    country: 'Uganda', flag: '🇺🇬', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Medicine, Health Sciences, Social Sciences, Community Work',
    description: 'Mastercard Foundation partner. One of Africa\'s oldest and most prestigious universities in Kampala, Uganda.',
    link: 'https://www.mak.ac.ug',
    tags: ['Mastercard', 'Medicine', 'Health Sciences', 'Community'],
  },
  {
    id: 6,
    name: 'University of Cape Town (UCT)',
    country: 'South Africa', flag: '🇿🇦', region: 'africa',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Environmental Science, Climate Studies, Leadership',
    description: 'Mastercard Foundation partner. Africa\'s top-ranked university — postgraduate scholarships in environmental science and leadership.',
    link: 'https://www.uct.ac.za',
    tags: ['Mastercard', 'Top Ranked', 'Climate', 'Environment'],
  },
  {
    id: 7,
    name: 'University of Pretoria',
    country: 'South Africa', flag: '🇿🇦', region: 'africa',
    category: 'mastercard', level: 'Undergrad / Postgrad', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Agriculture, Engineering, Social Development',
    description: 'Mastercard Foundation partner. Leading research university in Southern Africa with strong agriculture and engineering programs.',
    link: 'https://www.up.ac.za',
    tags: ['Mastercard', 'Agriculture', 'Engineering', 'Research'],
  },
  {
    id: 8,
    name: 'University of the Western Cape',
    country: 'South Africa', flag: '🇿🇦', region: 'africa',
    category: 'mastercard', level: 'Undergrad / Postgrad', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Social Sciences, Community Development, Leadership',
    description: 'Mastercard Foundation partner. Known for social justice, community development and leadership programs.',
    link: 'https://www.uwc.ac.za',
    tags: ['Mastercard', 'Social Sciences', 'Community', 'Leadership'],
  },
  {
    id: 9,
    name: 'University of Rwanda',
    country: 'Rwanda', flag: '🇷🇼', region: 'africa',
    category: 'mastercard', level: 'Undergrad / Postgrad', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Business, IT, Social Sciences, Community Development',
    description: 'Mastercard Foundation partner. Rwanda\'s flagship national university with strong IT, business and social sciences programs.',
    link: 'https://www.ur.ac.rw',
    tags: ['Mastercard', 'IT', 'Business', 'Social Sciences'],
  },
  {
    id: 10,
    name: 'University of Gondar',
    country: 'Ethiopia', flag: '🇪🇹', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Medicine, Public Health, Community Support',
    description: 'Mastercard Foundation partner. Leading health sciences and medicine university in northern Ethiopia.',
    link: 'https://www.uog.edu.et',
    tags: ['Mastercard', 'Medicine', 'Public Health', 'Community'],
  },
  {
    id: 11,
    name: 'University of Abomey-Calavi',
    country: 'Benin', flag: '🇧🇯', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Business, IT, Education & Social Sciences',
    description: 'Mastercard Foundation partner. Largest university in Benin — applications currently open for African students.',
    link: 'https://www.uac.bj',
    tags: ['Mastercard', 'IT', 'Business', 'Education'],
  },
  {
    id: 12,
    name: 'Pan-Atlantic University',
    country: 'Nigeria', flag: '🇳🇬', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Business for Social Good',
    description: 'Mastercard Foundation partner. Business and leadership university in Lagos, Nigeria — applications open.',
    link: 'https://www.pau.edu.ng',
    tags: ['Mastercard', 'Business', 'Leadership', 'Social Good'],
  },
  {
    id: 13,
    name: 'USIU-Africa',
    country: 'Kenya', flag: '🇰🇪', region: 'africa',
    category: 'mastercard', level: 'Undergraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Business, Social Sciences, Leadership',
    description: 'United States International University-Africa. Mastercard partner — US-accredited university in Nairobi.',
    link: 'https://www.usiu.ac.ke',
    tags: ['Mastercard', 'US-Accredited', 'Business', 'Social Sciences'],
  },
  {
    id: 14,
    name: 'Université Mohammed VI Polytechnique',
    country: 'Morocco', flag: '🇲🇦', region: 'africa',
    category: 'mastercard', level: 'Undergrad / Postgrad', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Engineering, Tech, Entrepreneurship',
    description: 'Mastercard Foundation partner. Leading polytechnic university in North Africa focused on engineering and entrepreneurship.',
    link: 'https://www.um6p.ma',
    tags: ['Mastercard', 'Engineering', 'Technology', 'Entrepreneurship'],
  },
  {
    id: 15,
    name: 'Université Gaston Berger',
    country: 'Senegal', flag: '🇸🇳', region: 'africa',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Social Sciences, Community Development',
    description: 'Mastercard Foundation partner. Research university in Saint-Louis, Senegal — postgraduate focus.',
    link: 'https://ugb.sn',
    tags: ['Mastercard', 'Social Sciences', 'Community', 'Francophone'],
  },
  {
    id: 16,
    name: '2iE — Water & Environmental Engineering',
    country: 'Burkina Faso', flag: '🇧🇫', region: 'africa',
    category: 'mastercard', level: 'Undergrad / Postgrad', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Water Engineering, Environmental Sciences',
    description: 'International Institute for Water and Environmental Engineering. Mastercard partner — specialist institute in West Africa.',
    link: 'https://www.2ie-edu.org',
    tags: ['Mastercard', 'Water Engineering', 'Environment', 'Sciences'],
  },
  {
    id: 17,
    name: 'University of Global Health Equity',
    country: 'Rwanda', flag: '🇷🇼', region: 'africa',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Public Health, Health Systems, Social Impact',
    description: 'Mastercard Foundation partner. Health equity-focused graduate university in Butaro, Rwanda.',
    link: 'https://ughe.org',
    tags: ['Mastercard', 'Public Health', 'Health Systems', 'Social Impact'],
  },
  {
    id: 18,
    name: 'AIMS — African Institute for Mathematical Sciences',
    country: 'Africa (Multiple)', flag: '🌍', region: 'africa',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Mathematics, Data Science, AI',
    description: 'Mastercard Foundation partner. Pan-African network of centres for mathematical sciences, data science and AI.',
    link: 'https://nexteinstein.org',
    tags: ['Mastercard', 'Mathematics', 'Data Science', 'AI'],
  },
  {
    id: 19,
    name: 'Carnegie Mellon University Africa',
    country: 'Rwanda', flag: '🇷🇼', region: 'africa',
    category: 'mastercard', level: 'Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Software Engineering, AI, Data Science, Cybersecurity',
    description: 'Mastercard Foundation partner. CMU\'s African campus in Kigali — world-class tech graduate programs. Applications open.',
    link: 'https://africa.engineering.cmu.edu',
    tags: ['Mastercard', 'Software Engineering', 'AI', 'CMU', 'Cybersecurity'],
  },

  // ════════════════════════════════════════════════════════════
  // MASTERCARD FOUNDATION — ABROAD (USA)
  // ════════════════════════════════════════════════════════════
  {
    id: 20,
    name: 'Arizona State University (ASU)',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'mastercard', level: 'Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Tech & Innovation for Development, Leadership, Computing',
    description: 'Mastercard Foundation partner. Top US public university known for innovation — postgraduate applications open.',
    link: 'https://www.asu.edu',
    tags: ['Mastercard', 'Computing', 'Innovation', 'Leadership'],
  },
  {
    id: 21,
    name: 'UC Berkeley',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'mastercard', level: 'Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Data Science, Leadership',
    description: 'Mastercard Foundation partner. World-renowned public research university in California — postgraduate applications open.',
    link: 'https://www.berkeley.edu',
    tags: ['Mastercard', 'Computer Science', 'Data Science', 'Research'],
  },
  {
    id: 22,
    name: 'Duke University',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'mastercard', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Global Development, Policy',
    description: 'Mastercard Foundation partner. Elite research university in North Carolina — check website for current window.',
    link: 'https://www.duke.edu',
    tags: ['Mastercard', 'Leadership', 'Global Development', 'Policy'],
  },
  {
    id: 23,
    name: 'Stanford University',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'mastercard', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Social Innovation, Leadership, Technology',
    description: 'Mastercard Foundation partner. World\'s leading innovation and technology university.',
    link: 'https://www.stanford.edu',
    tags: ['Mastercard', 'Social Innovation', 'Technology', 'Leadership'],
  },
  {
    id: 24,
    name: 'Wellesley College',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'mastercard', level: 'Undergraduate', window: 'check',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: "Leadership, Women's Studies, Social Impact",
    description: "Mastercard Foundation partner. Elite women's liberal arts college near Boston, Massachusetts.",
    link: 'https://www.wellesley.edu',
    tags: ["Mastercard", "Women's College", "Leadership", "Social Impact"],
  },

  // ════════════════════════════════════════════════════════════
  // MASTERCARD FOUNDATION — ABROAD (CANADA)
  // ════════════════════════════════════════════════════════════
  {
    id: 25,
    name: 'McGill University',
    country: 'Canada', flag: '🇨🇦', region: 'canada',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Leadership, Innovation',
    description: "Mastercard Foundation partner. Canada's top-ranked university in Montreal.",
    link: 'https://www.mcgill.ca',
    tags: ['Mastercard', 'Canada', 'Computer Science', 'Innovation'],
  },
  {
    id: 26,
    name: 'University of Toronto',
    country: 'Canada', flag: '🇨🇦', region: 'canada',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'AI, Computing, Leadership',
    description: "Mastercard Foundation partner. Canada's largest research university — strong AI and computing programs.",
    link: 'https://www.utoronto.ca',
    tags: ['Mastercard', 'Canada', 'AI', 'Computing'],
  },
  {
    id: 27,
    name: 'University of British Columbia (UBC)',
    country: 'Canada', flag: '🇨🇦', region: 'canada',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computing, Engineering, Social Policies',
    description: 'Mastercard Foundation partner. World-class university in Vancouver — computing, engineering and social policy.',
    link: 'https://www.ubc.ca',
    tags: ['Mastercard', 'Canada', 'Computing', 'Engineering'],
  },

  // ════════════════════════════════════════════════════════════
  // MASTERCARD FOUNDATION — ABROAD (UK & EUROPE)
  // ════════════════════════════════════════════════════════════
  {
    id: 28,
    name: 'University of Cambridge',
    country: 'United Kingdom', flag: '🇬🇧', region: 'uk',
    category: 'mastercard', level: 'Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Leadership, Innovation',
    description: "Mastercard Foundation partner. One of the world's oldest universities — postgraduate applications open.",
    link: 'https://www.cam.ac.uk',
    tags: ['Mastercard', 'Top Ranked', 'Computer Science', 'Innovation'],
  },
  {
    id: 29,
    name: 'University of Oxford',
    country: 'United Kingdom', flag: '🇬🇧', region: 'uk',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Public Policy, Social Impact',
    description: "Mastercard Foundation partner. World's top-ranked university — leadership and social impact focus.",
    link: 'https://www.ox.ac.uk',
    tags: ['Mastercard', 'Top Ranked', '#1 World', 'Public Policy'],
  },
  {
    id: 30,
    name: 'University of Edinburgh',
    country: 'United Kingdom', flag: '🇬🇧', region: 'uk',
    category: 'mastercard', level: 'Postgraduate', window: 'closed',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Innovation & Development',
    description: "Mastercard Foundation partner. Scotland's most prestigious university.",
    link: 'https://www.ed.ac.uk',
    tags: ['Mastercard', 'Scotland', 'Leadership', 'Innovation'],
  },
  {
    id: 31,
    name: 'Sciences Po',
    country: 'France', flag: '🇫🇷', region: 'europe',
    category: 'mastercard', level: 'Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Governance, Policy, Social Entrepreneurship',
    description: "Mastercard Foundation partner. France's top social and political sciences university — applications open.",
    link: 'https://www.sciencespo.fr',
    tags: ['Mastercard', 'Governance', 'Policy', 'Social Entrepreneurship'],
  },

  // ════════════════════════════════════════════════════════════
  // MASTERCARD FOUNDATION — ABROAD (OTHER REGIONS)
  // ════════════════════════════════════════════════════════════
  {
    id: 32,
    name: 'American University of Beirut (AUB)',
    country: 'Lebanon', flag: '🇱🇧', region: 'other',
    category: 'mastercard', level: 'Undergraduate / Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Social Change, Community Development',
    description: 'Mastercard Foundation partner. Leading university in Beirut — applications open for African students.',
    link: 'https://www.aub.edu.lb',
    tags: ['Mastercard', 'Leadership', 'Social Change', 'Community'],
  },
  {
    id: 33,
    name: 'EARTH University',
    country: 'Costa Rica', flag: '🇨🇷', region: 'other',
    category: 'mastercard', level: 'Undergraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Sustainable Agriculture, Community Empowerment',
    description: 'Mastercard Foundation partner. Unique university focused on sustainable agriculture and community empowerment.',
    link: 'https://www.earth.ac.cr',
    tags: ['Mastercard', 'Agriculture', 'Sustainability', 'Community'],
  },

  // ════════════════════════════════════════════════════════════
  {
    id: 34, name: 'ALCHE — African Leadership College of Higher Education',
    country: 'South Africa', flag: '🇿🇦',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Entrepreneurship, Social Impact, Business',
    description: 'Mastercard Foundation partner. African leadership college in South Africa developing the next generation of entrepreneurs and changemakers.',
    link: 'https://www.alcheducation.com',
    tags: ["Mastercard", "Leadership", "Entrepreneurship"],
  },

  // FULLY FUNDED — WORK COLLEGES (USA)
  // ════════════════════════════════════════════════════════════
  {
    id: 34,
    name: 'Berea College',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Undergraduate', window: 'check',
    funding: '⭐ No Tuition — Work College',
    focus: 'Service Learning, Community Engagement, Leadership',
    description: 'Every admitted student receives full tuition free. Students work on campus to cover costs. Best guaranteed fully funded option for African students.',
    link: 'https://www.berea.edu',
    tags: ['Work College', 'No Tuition', '⭐ Best Option', 'Community'],
  },
  {
    id: 35,
    name: 'College of the Ozarks',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Undergraduate', window: 'check',
    funding: '⭐ No Tuition — Work College',
    focus: 'Service, Leadership, Community Development',
    description: 'Called "Hard Work U" — students work instead of paying tuition. Highly recommended for African students seeking guaranteed full funding.',
    link: 'https://www.cofo.edu',
    tags: ['Work College', 'No Tuition', '⭐ Best Option', 'Leadership'],
  },
  {
    id: 36,
    name: 'Alice Lloyd College',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Undergraduate', window: 'check',
    funding: 'No Tuition — Work College',
    focus: 'Leadership, Rural Community Support',
    description: 'Work college in Kentucky. Free tuition for all students in exchange for campus work. Good option for African students.',
    link: 'https://alc.edu',
    tags: ['Work College', 'No Tuition', 'Leadership', 'Community'],
  },

  // ════════════════════════════════════════════════════════════
  // FULLY FUNDED — IVY LEAGUE & TOP US (Need-Based Aid)
  // ════════════════════════════════════════════════════════════
  {
    id: 37,
    name: 'Harvard University',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Social Innovation, Global Development, Leadership',
    description: 'Meets 100% of demonstrated financial need for all admitted students worldwide. Highly competitive — apply with Mastercard unis as backup.',
    link: 'https://www.harvard.edu',
    tags: ['Ivy League', 'Need-Based', 'Top Ranked', 'Competitive'],
  },
  {
    id: 38,
    name: 'Yale University',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Leadership, Public Policy, Social Justice',
    description: 'Ivy League. Meets 100% of demonstrated financial need for all admitted students.',
    link: 'https://www.yale.edu',
    tags: ['Ivy League', 'Need-Based', 'Top Ranked', 'Public Policy'],
  },
  {
    id: 39,
    name: 'Princeton University',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded / Need-Based Aid — No Loans Policy',
    focus: 'Leadership, Global Development, Policy',
    description: 'Ivy League with a no-loan policy — all financial aid given as grants, not loans. Exceptionally generous for international students.',
    link: 'https://www.princeton.edu',
    tags: ['Ivy League', 'No Loans', 'Top Ranked', 'Policy'],
  },
  {
    id: 40,
    name: 'Columbia University',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Social Innovation, Leadership, Policy',
    description: 'Ivy League in New York City. Meets 100% of demonstrated financial need for all admitted international students.',
    link: 'https://www.columbia.edu',
    tags: ['Ivy League', 'Need-Based', 'NYC', 'Social Innovation'],
  },
  {
    id: 41,
    name: 'MIT',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Technology & Social Innovation',
    description: "World's #1 tech university. Meets 100% of demonstrated financial need for all students worldwide.",
    link: 'https://web.mit.edu',
    tags: ['STEM', 'Technology', 'Need-Based', 'Top Ranked', 'Innovation'],
  },
  {
    id: 42,
    name: 'Colorado College',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'fullyfunded', level: 'Undergraduate', window: 'check',
    funding: 'Partial Aid — Not Fully Guaranteed',
    focus: 'Liberal Arts, Community Engagement',
    description: 'Liberal arts college via Common App. Partial funding available — not fully guaranteed. Apply alongside stronger options.',
    link: 'https://www.commonapp.org',
    tags: ['Liberal Arts', 'Partial Aid', 'Community', 'Common App'],
  },

  // ════════════════════════════════════════════════════════════
  // GLOBAL SCHOLARSHIP PROGRAMS
  // ════════════════════════════════════════════════════════════
  {
    id: 43,
    name: 'Mastercard Foundation Scholars Program',
    country: 'Global', flag: '🌍', region: 'other',
    category: 'global', level: 'Undergraduate & Postgraduate', window: 'open',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Social Impact, Any Discipline — via partner universities',
    description: 'The main Mastercard Foundation Scholars Program covering all partner universities listed above. Central application hub.',
    link: 'https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/',
    tags: ['Mastercard', 'Global', 'Leadership', 'Social Impact'],
  },
  {
    id: 44,
    name: 'Fulbright Program',
    country: 'USA', flag: '🇺🇸', region: 'usa',
    category: 'global', level: 'Postgraduate + Research', window: 'check',
    funding: 'Fully Funded by US Government',
    focus: 'Any Discipline — Research, Public Policy, Technology',
    description: "US government's flagship international exchange scholarship. Full funding to study at top US universities. One of the world's most prestigious awards.",
    link: 'https://foreign.fulbrightonline.org',
    tags: ['US Government', 'Prestigious', 'Research', 'Exchange'],
  },
  {
    id: 45,
    name: 'Chevening Scholarships',
    country: 'United Kingdom', flag: '🇬🇧', region: 'uk',
    category: 'global', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded by UK Government',
    focus: 'Leadership, Any Discipline',
    description: "UK government's global scholarship for future leaders. Full funding to study at any UK university — open to Africans.",
    link: 'https://www.chevening.org',
    tags: ['UK Government', 'Leadership', 'Prestigious', 'Future Leaders'],
  },
  {
    id: 46,
    name: 'Commonwealth Scholarships',
    country: 'UK / Commonwealth', flag: '🌍', region: 'uk',
    category: 'global', level: 'Postgraduate + PhD', window: 'check',
    funding: 'Fully Funded',
    focus: 'Any Discipline — Commonwealth Nations',
    description: 'For students from Commonwealth countries including most African nations. Full funding to study in the UK.',
    link: 'https://cscuk.fcdo.gov.uk',
    tags: ['Commonwealth', 'UK', 'PhD', 'Postgraduate'],
  },
  {
    id: 47,
    name: 'Erasmus Mundus Joint Masters',
    country: 'Europe', flag: '🇪🇺', region: 'europe',
    category: 'global', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded by European Union',
    focus: 'Any Discipline — Study across Multiple European Countries',
    description: 'EU-funded scholarship to study in multiple European countries. Full tuition + living allowance + travel costs paid.',
    link: 'https://ec.europa.eu/education/external-activities/erasmus-mundus_en',
    tags: ['EU Funded', 'Multiple Countries', 'Europe', 'Joint Masters'],
  },
  {
    id: 48,
    name: 'DAAD Scholarships',
    country: 'Germany', flag: '🇩🇪', region: 'europe',
    category: 'global', level: 'Undergraduate & Postgraduate', window: 'check',
    funding: 'Fully Funded by Germany',
    focus: 'Engineering, Science, Social Sciences, Arts',
    description: 'German Academic Exchange Service. Full scholarship covering tuition, living costs and travel for international students.',
    link: 'https://www.daad.de/en/',
    tags: ['Germany', 'Government Funded', 'Engineering', 'Sciences'],
  },
  {
    id: 49,
    name: 'Oxford — AfOx / Clarendon Scholarship',
    country: 'United Kingdom', flag: '🇬🇧', region: 'uk',
    category: 'global', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded',
    focus: 'Any Discipline — AfOx specifically for African students',
    description: "Africa Oxford Initiative (AfOx) scholarship is specifically designed for African students at Oxford. Covers fees and full living costs.",
    link: 'https://www.ox.ac.uk/clarendon',
    tags: ['Oxford', 'Africa Focus', 'Prestigious', 'AfOx'],
  },
  {
    id: 50,
    name: 'Gates Cambridge Scholarship',
    country: 'United Kingdom', flag: '🇬🇧', region: 'uk',
    category: 'global', level: 'Postgraduate', window: 'check',
    funding: 'Fully Funded by Bill Gates Foundation',
    focus: 'Any Discipline — Leadership & Social Impact Focus',
    description: 'Bill Gates-funded scholarship at Cambridge University. Full funding for outstanding international students with leadership potential.',
    link: 'https://www.gatescambridge.org',
    tags: ['Cambridge', 'Gates', 'Prestigious', 'Leadership'],
  },
];
