/* ══════════════════════════════════════════════════════════════
   data.js — 50 curated scholarships (static data, no API needed)
   Sources: Mastercard Foundation, Fully Funded programs,
            Global Scholarships
   Project: HopeScholar
   Author:  Gabriel Mugisha | ALU | gabrielmugisha.tech
   ══════════════════════════════════════════════════════════════ */

'use strict';

const SCHOLARSHIPS = [

  // ── MASTERCARD FOUNDATION — AFRICA ─────────────────────────
  {
    id: 1, name: 'African Leadership University (ALU)',
    country: 'Rwanda / Mauritius', flag: '🇷🇼',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Social Impact, Entrepreneurship, Software Engineering',
    description: 'Mastercard Foundation Scholars Program partner. Innovative competency-based education developing ethical, entrepreneurial African leaders at zero cost.',
    link: 'https://www.alueducation.com',
    tags: ['Mastercard', 'Leadership', 'Software Engineering'],
  },
  {
    id: 2, name: 'African Leadership Academy',
    country: 'South Africa', flag: '🇿🇦',
    region: 'africa', category: 'mastercard', level: 'Pre-University / Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Entrepreneurship, Community Projects',
    description: 'Mastercard Foundation partner. Two-year pre-university program developing Africa\'s next generation of leaders.',
    link: 'https://www.africanleadershipacademy.org',
    tags: ['Mastercard', 'Leadership', 'Entrepreneurship'],
  },
  {
    id: 3, name: 'Ashesi University',
    country: 'Ghana', flag: '🇬🇭',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Leadership, Business, Social Impact',
    description: 'Mastercard Foundation partner. Liberal arts and engineering university focused on ethical leadership in Ghana.',
    link: 'https://www.ashesi.edu.gh',
    tags: ['Mastercard', 'Computer Science', 'Business'],
  },
  {
    id: 4, name: 'KNUST',
    country: 'Ghana', flag: '🇬🇭',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Engineering, Science, Technology, Leadership',
    description: 'Kwame Nkrumah University of Science and Technology. Mastercard partner — premier STEM university in West Africa.',
    link: 'https://www.knust.edu.gh',
    tags: ['Mastercard', 'Engineering', 'STEM'],
  },
  {
    id: 5, name: 'Makerere University',
    country: 'Uganda', flag: '🇺🇬',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Medicine, Health Sciences, Social Sciences, Community Work',
    description: 'Mastercard Foundation partner. One of Africa\'s oldest and most prestigious universities in Kampala.',
    link: 'https://www.mak.ac.ug',
    tags: ['Mastercard', 'Medicine', 'Health Sciences'],
  },
  {
    id: 6, name: 'University of Cape Town (UCT)',
    country: 'South Africa', flag: '🇿🇦',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Environmental Science, Climate Studies, Leadership',
    description: 'Mastercard Foundation partner. Africa\'s top-ranked university — postgraduate scholarships in environmental science.',
    link: 'https://www.uct.ac.za',
    tags: ['Mastercard', 'Top Ranked', 'Climate'],
  },
  {
    id: 7, name: 'University of Pretoria',
    country: 'South Africa', flag: '🇿🇦',
    region: 'africa', category: 'mastercard', level: 'Undergrad / Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Agriculture, Engineering, Social Development',
    description: 'Mastercard Foundation partner. Leading research university in Southern Africa.',
    link: 'https://www.up.ac.za',
    tags: ['Mastercard', 'Agriculture', 'Engineering'],
  },
  {
    id: 8, name: 'University of the Western Cape',
    country: 'South Africa', flag: '🇿🇦',
    region: 'africa', category: 'mastercard', level: 'Undergrad / Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Social Sciences, Community Development, Leadership',
    description: 'Mastercard Foundation partner. Known for social justice, community development and leadership.',
    link: 'https://www.uwc.ac.za',
    tags: ['Mastercard', 'Social Sciences', 'Community'],
  },
  {
    id: 9, name: 'University of Rwanda',
    country: 'Rwanda', flag: '🇷🇼',
    region: 'africa', category: 'mastercard', level: 'Undergrad / Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Business, IT, Social Sciences, Community Development',
    description: 'Mastercard Foundation partner. Rwanda\'s flagship national university with IT and business programs.',
    link: 'https://www.ur.ac.rw',
    tags: ['Mastercard', 'IT', 'Business'],
  },
  {
    id: 10, name: 'University of Gondar',
    country: 'Ethiopia', flag: '🇪🇹',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Medicine, Public Health, Community Support',
    description: 'Mastercard Foundation partner. Leading health sciences university in northern Ethiopia.',
    link: 'https://www.uog.edu.et',
    tags: ['Mastercard', 'Medicine', 'Public Health'],
  },
  {
    id: 11, name: 'University of Abomey-Calavi',
    country: 'Benin', flag: '🇧🇯',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Business, IT, Education & Social Sciences',
    description: 'Mastercard Foundation partner. Largest university in Benin — visit website to check applications.',
    link: 'https://www.uac.bj',
    tags: ['Mastercard', 'IT', 'Business'],
  },
  {
    id: 12, name: 'Pan-Atlantic University',
    country: 'Nigeria', flag: '🇳🇬',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Business for Social Good',
    description: 'Mastercard Foundation partner. Business and leadership university in Lagos, Nigeria.',
    link: 'https://www.pau.edu.ng',
    tags: ['Mastercard', 'Business', 'Leadership'],
  },
  {
    id: 13, name: 'USIU-Africa',
    country: 'Kenya', flag: '🇰🇪',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Business, Social Sciences, Leadership',
    description: 'United States International University-Africa. Mastercard partner — US-accredited university in Nairobi.',
    link: 'https://www.usiu.ac.ke',
    tags: ['Mastercard', 'US-Accredited', 'Business'],
  },
  {
    id: 14, name: 'Université Mohammed VI Polytechnique',
    country: 'Morocco', flag: '🇲🇦',
    region: 'africa', category: 'mastercard', level: 'Undergrad / Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Engineering, Tech, Entrepreneurship',
    description: 'Mastercard Foundation partner. Leading polytechnic university in North Africa.',
    link: 'https://www.um6p.ma',
    tags: ['Mastercard', 'Engineering', 'Technology'],
  },
  {
    id: 15, name: 'Université Gaston Berger',
    country: 'Senegal', flag: '🇸🇳',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Social Sciences, Community Development',
    description: 'Mastercard Foundation partner. Research university in Saint-Louis, Senegal.',
    link: 'https://ugb.sn',
    tags: ['Mastercard', 'Social Sciences', 'Francophone'],
  },
  {
    id: 16, name: '2iE — Water & Environmental Engineering',
    country: 'Burkina Faso', flag: '🇧🇫',
    region: 'africa', category: 'mastercard', level: 'Undergrad / Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Water Engineering, Environmental Sciences',
    description: 'International Institute for Water and Environmental Engineering. Mastercard partner in West Africa.',
    link: 'https://www.2ie-edu.org',
    tags: ['Mastercard', 'Water Engineering', 'Environment'],
  },
  {
    id: 17, name: 'University of Global Health Equity',
    country: 'Rwanda', flag: '🇷🇼',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Public Health, Health Systems, Social Impact',
    description: 'Mastercard Foundation partner. Health equity-focused graduate university in Butaro, Rwanda.',
    link: 'https://ughe.org',
    tags: ['Mastercard', 'Public Health', 'Social Impact'],
  },
  {
    id: 18, name: 'AIMS — African Institute for Mathematical Sciences',
    country: 'Africa (Multiple)', flag: '🌍',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Mathematics, Data Science, AI',
    description: 'Mastercard Foundation partner. Pan-African network for mathematical sciences, data science and AI.',
    link: 'https://nexteinstein.org',
    tags: ['Mastercard', 'Mathematics', 'Data Science', 'AI'],
  },
  {
    id: 19, name: 'Carnegie Mellon University Africa',
    country: 'Rwanda', flag: '🇷🇼',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Software Engineering, AI, Data Science, Cybersecurity',
    description: 'Mastercard Foundation partner. CMU\'s African campus in Kigali — world-class tech graduate programs.',
    link: 'https://africa.engineering.cmu.edu',
    tags: ['Mastercard', 'Software Engineering', 'AI', 'CMU'],
  },
  // ── MASTERCARD — USA ────────────────────────────────────────
  {
    id: 20, name: 'Arizona State University (ASU)',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Tech & Innovation for Development, Leadership, Computing',
    description: 'Mastercard Foundation partner. Top US public university — tech and innovation for development.',
    link: 'https://www.asu.edu',
    tags: ['Mastercard', 'Computing', 'Innovation'],
  },
  {
    id: 21, name: 'UC Berkeley',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Data Science, Leadership',
    description: 'Mastercard Foundation partner. World-renowned public research university in California.',
    link: 'https://www.berkeley.edu',
    tags: ['Mastercard', 'Computer Science', 'Data Science'],
  },
  {
    id: 22, name: 'Duke University',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Global Development, Policy',
    description: 'Mastercard Foundation partner. Elite research university in North Carolina.',
    link: 'https://www.duke.edu',
    tags: ['Mastercard', 'Leadership', 'Global Development'],
  },
  {
    id: 23, name: 'Stanford University',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Social Innovation, Leadership, Technology',
    description: 'Mastercard Foundation partner. World\'s leading innovation university.',
    link: 'https://www.stanford.edu',
    tags: ['Mastercard', 'Social Innovation', 'Technology'],
  },
  {
    id: 24, name: 'Wellesley College',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: "Leadership, Women's Studies, Social Impact",
    description: "Mastercard Foundation partner. Elite women's liberal arts college near Boston.",
    link: 'https://www.wellesley.edu',
    tags: ['Mastercard', "Women's College", 'Leadership'],
  },
  // ── MASTERCARD — CANADA ─────────────────────────────────────
  {
    id: 25, name: 'McGill University',
    country: 'Canada', flag: '🇨🇦',
    region: 'canada', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Leadership, Innovation',
    description: "Mastercard Foundation partner. Canada's top-ranked university in Montreal.",
    link: 'https://www.mcgill.ca',
    tags: ['Mastercard', 'Canada', 'Computer Science'],
  },
  {
    id: 26, name: 'University of Toronto',
    country: 'Canada', flag: '🇨🇦',
    region: 'canada', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'AI, Computing, Leadership',
    description: "Mastercard Foundation partner. Canada's largest research university — strong AI and computing.",
    link: 'https://www.utoronto.ca',
    tags: ['Mastercard', 'Canada', 'AI', 'Computing'],
  },
  {
    id: 27, name: 'University of British Columbia (UBC)',
    country: 'Canada', flag: '🇨🇦',
    region: 'canada', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computing, Engineering, Social Policies',
    description: 'Mastercard Foundation partner. World-class university in Vancouver.',
    link: 'https://www.ubc.ca',
    tags: ['Mastercard', 'Canada', 'Computing', 'Engineering'],
  },
  // ── MASTERCARD — UK ─────────────────────────────────────────
  {
    id: 28, name: 'University of Cambridge',
    country: 'United Kingdom', flag: '🇬🇧',
    region: 'uk', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Computer Science, Leadership, Innovation',
    description: "Mastercard Foundation partner. One of the world's oldest and most prestigious universities.",
    link: 'https://www.cam.ac.uk',
    tags: ['Mastercard', 'Top Ranked', 'Computer Science'],
  },
  {
    id: 29, name: 'University of Oxford',
    country: 'United Kingdom', flag: '🇬🇧',
    region: 'uk', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Public Policy, Social Impact',
    description: "Mastercard Foundation partner. World's #1 ranked university.",
    link: 'https://www.ox.ac.uk',
    tags: ['Mastercard', 'Top Ranked', '#1 World'],
  },
  {
    id: 30, name: 'University of Edinburgh',
    country: 'United Kingdom', flag: '🇬🇧',
    region: 'uk', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Innovation & Development',
    description: "Mastercard Foundation partner. Scotland's most prestigious university.",
    link: 'https://www.ed.ac.uk',
    tags: ['Mastercard', 'Scotland', 'Leadership'],
  },
  // ── MASTERCARD — EUROPE & OTHER ─────────────────────────────
  {
    id: 31, name: 'Sciences Po',
    country: 'France', flag: '🇫🇷',
    region: 'europe', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Governance, Policy, Social Entrepreneurship',
    description: "Mastercard Foundation partner. France's top social and political sciences university.",
    link: 'https://www.sciencespo.fr',
    tags: ['Mastercard', 'Governance', 'Policy'],
  },
  {
    id: 32, name: 'American University of Beirut (AUB)',
    country: 'Lebanon', flag: '🇱🇧',
    region: 'other', category: 'mastercard', level: 'Undergraduate / Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Social Change, Community Development',
    description: 'Mastercard Foundation partner. Leading university in Beirut — open to African students.',
    link: 'https://www.aub.edu.lb',
    tags: ['Mastercard', 'Leadership', 'Social Change'],
  },
  {
    id: 33, name: 'EARTH University',
    country: 'Costa Rica', flag: '🇨🇷',
    region: 'other', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Sustainable Agriculture, Community Empowerment',
    description: 'Mastercard Foundation partner. Unique university focused on sustainable agriculture and community empowerment.',
    link: 'https://www.earth.ac.cr',
    tags: ['Mastercard', 'Agriculture', 'Sustainability'],
  },
  // ── FULLY FUNDED — WORK COLLEGES ────────────────────────────
  {
    id: 34, name: 'Berea College',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: '⭐ No Tuition — Work College',
    focus: 'Service Learning, Community Engagement, Leadership',
    description: 'Every admitted student receives full tuition free. Students work on campus. Best guaranteed fully funded option for African students from poor communities.',
    link: 'https://www.berea.edu',
    tags: ['Work College', 'No Tuition', '⭐ Best Option'],
  },
  {
    id: 35, name: 'College of the Ozarks',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: '⭐ No Tuition — Work College',
    focus: 'Service, Leadership, Community Development',
    description: 'Called "Hard Work U" — students work instead of paying tuition. Highly recommended for African students.',
    link: 'https://www.cofo.edu',
    tags: ['Work College', 'No Tuition', '⭐ Best Option'],
  },
  {
    id: 36, name: 'Alice Lloyd College',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: 'No Tuition — Work College',
    focus: 'Leadership, Rural Community Support',
    description: 'Work college in Kentucky. Free tuition for all students in exchange for campus work.',
    link: 'https://alc.edu',
    tags: ['Work College', 'No Tuition', 'Leadership'],
  },
  // ── FULLY FUNDED — IVY LEAGUE & TOP US ──────────────────────
  {
    id: 37, name: 'Harvard University',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Postgraduate',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Social Innovation, Global Development, Leadership',
    description: 'Meets 100% of demonstrated financial need for all admitted students worldwide. Highly competitive.',
    link: 'https://www.harvard.edu',
    tags: ['Ivy League', 'Need-Based', 'Top Ranked'],
  },
  {
    id: 38, name: 'Yale University',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Postgraduate',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Leadership, Public Policy, Social Justice',
    description: 'Ivy League. Meets 100% of demonstrated financial need for all admitted students.',
    link: 'https://www.yale.edu',
    tags: ['Ivy League', 'Need-Based', 'Top Ranked'],
  },
  {
    id: 39, name: 'Princeton University',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Postgraduate',
    funding: 'Fully Funded / Need-Based Aid — No Loans',
    focus: 'Leadership, Global Development, Policy',
    description: 'Ivy League. No-loan policy — all aid given as grants. Exceptionally generous for international students.',
    link: 'https://www.princeton.edu',
    tags: ['Ivy League', 'No Loans', 'Top Ranked'],
  },
  {
    id: 40, name: 'Columbia University',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Postgraduate',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Social Innovation, Leadership, Policy',
    description: 'Ivy League in New York City. Meets 100% of demonstrated financial need.',
    link: 'https://www.columbia.edu',
    tags: ['Ivy League', 'Need-Based', 'NYC'],
  },
  {
    id: 41, name: 'MIT',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Postgraduate',
    funding: 'Fully Funded / Need-Based Aid',
    focus: 'Technology & Social Innovation',
    description: "World's #1 tech university. Meets 100% of demonstrated financial need for all students.",
    link: 'https://web.mit.edu',
    tags: ['STEM', 'Technology', 'Need-Based', 'Top Ranked'],
  },
  {
    id: 42, name: 'Colorado College',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: 'Partial Aid — Not Fully Guaranteed',
    focus: 'Liberal Arts, Community Engagement',
    description: 'Liberal arts college via Common App. Partial funding available — apply alongside stronger options.',
    link: 'https://www.commonapp.org',
    tags: ['Liberal Arts', 'Partial Aid', 'Community'],
  },
  // ── GLOBAL SCHOLARSHIP PROGRAMS ─────────────────────────────
  {
    id: 43, name: 'Mastercard Foundation Scholars Program',
    country: 'Global', flag: '🌍',
    region: 'other', category: 'global', level: 'Undergraduate & Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: 'Leadership, Social Impact, Any Discipline — via partner universities',
    description: 'Central hub for the Mastercard Foundation Scholars Program covering all partner universities. Start your application here.',
    link: 'https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/',
    tags: ['Mastercard', 'Global', 'Leadership'],
  },
  {
    id: 44, name: 'Fulbright Program',
    country: 'USA', flag: '🇺🇸',
    region: 'usa', category: 'global', level: 'Postgraduate + Research',
    funding: 'Fully Funded by US Government',
    focus: 'Any Discipline — Research, Public Policy, Technology',
    description: "US government's flagship international scholarship. Full funding to study at top US universities. One of the world's most prestigious awards.",
    link: 'https://foreign.fulbrightonline.org',
    tags: ['US Government', 'Prestigious', 'Research'],
  },
  {
    id: 45, name: 'Chevening Scholarships',
    country: 'United Kingdom', flag: '🇬🇧',
    region: 'uk', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded by UK Government',
    focus: 'Leadership, Any Discipline',
    description: "UK government's global scholarship for future leaders. Full funding to study at any UK university.",
    link: 'https://www.chevening.org',
    tags: ['UK Government', 'Leadership', 'Prestigious'],
  },
  {
    id: 46, name: 'Commonwealth Scholarships',
    country: 'UK / Commonwealth', flag: '🌍',
    region: 'uk', category: 'global', level: 'Postgraduate + PhD',
    funding: 'Fully Funded',
    focus: 'Any Discipline — Commonwealth Nations',
    description: 'For students from Commonwealth countries. Full funding to study in the UK and Commonwealth nations.',
    link: 'https://cscuk.fcdo.gov.uk',
    tags: ['Commonwealth', 'UK', 'PhD'],
  },
  {
    id: 47, name: 'Erasmus Mundus Joint Masters',
    country: 'Europe', flag: '🇪🇺',
    region: 'europe', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded by European Union',
    focus: 'Any Discipline — Study across Multiple European Countries',
    description: 'EU-funded scholarship to study in multiple European countries. Full tuition + living allowance + travel costs paid.',
    link: 'https://ec.europa.eu/education/external-activities/erasmus-mundus_en',
    tags: ['EU Funded', 'Multiple Countries', 'Europe'],
  },
  {
    id: 48, name: 'DAAD Scholarships',
    country: 'Germany', flag: '🇩🇪',
    region: 'europe', category: 'global', level: 'Undergraduate & Postgraduate',
    funding: 'Fully Funded by Germany',
    focus: 'Engineering, Science, Social Sciences, Arts',
    description: 'German Academic Exchange Service. Full scholarship covering tuition, living costs and travel.',
    link: 'https://www.daad.de/en/',
    tags: ['Germany', 'Government Funded', 'Engineering'],
  },
  {
    id: 49, name: 'Oxford — AfOx / Clarendon Scholarship',
    country: 'United Kingdom', flag: '🇬🇧',
    region: 'uk', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded',
    focus: 'Any Discipline — AfOx specifically for African students',
    description: 'Africa Oxford Initiative (AfOx) scholarship specifically designed for African students. Covers full fees and living costs.',
    link: 'https://www.ox.ac.uk/clarendon',
    tags: ['Oxford', 'Africa Focus', 'Prestigious'],
  },
  {
    id: 50, name: 'Gates Cambridge Scholarship',
    country: 'United Kingdom', flag: '🇬🇧',
    region: 'uk', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded by Bill Gates Foundation',
    focus: 'Any Discipline — Leadership & Social Impact Focus',
    description: 'Bill Gates-funded scholarship at Cambridge University. Full funding for outstanding international students.',
    link: 'https://www.gatescambridge.org',
    tags: ['Cambridge', 'Gates', 'Prestigious', 'Leadership'],
  },
];
