/* ══════════════════════════════════════════════════════════════
   data.js — 51 curated scholarships
   Project: HopeScholar | gabrielmugisha.tech
   Author:  Gabriel Mugisha | ALU Software Engineering
   ══════════════════════════════════════════════════════════════ */
'use strict';

const SCHOLARSHIPS = [

  // ── MASTERCARD FOUNDATION — AFRICA ─────────────────────────
  {
    id: 1,
    name: 'African Leadership University (ALU)',
    shortName: 'ALU',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/African_Leadership_University_logo.png/200px-African_Leadership_University_logo.png',
    country: 'Rwanda', flag: '🇷🇼', city: 'Kigali',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Social Impact', 'Entrepreneurship', 'Software Engineering'],
    description: 'Mastercard Foundation Scholars Program partner. Innovative competency-based education developing ethical, entrepreneurial African leaders at absolutely zero cost.',
    link: 'https://www.alueducation.com',
    tags: ['Mastercard', 'Leadership', 'Software Engineering'],
  },
  {
    id: 2,
    name: 'African Leadership Academy',
    shortName: 'ALA',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/89/African_Leadership_Academy_logo.png/200px-African_Leadership_Academy_logo.png',
    country: 'South Africa', flag: '🇿🇦', city: 'Johannesburg',
    region: 'africa', category: 'mastercard', level: 'Pre-University',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Entrepreneurship', 'Community Projects'],
    description: 'Mastercard Foundation partner. Two-year pre-university program in Johannesburg developing Africa\'s next generation of leaders.',
    link: 'https://www.africanleadershipacademy.org',
    tags: ['Mastercard', 'Leadership', 'Pre-University'],
  },
  {
    id: 3,
    name: 'ALCHE — African Leadership College',
    shortName: 'ALCHE',
    logo: 'https://www.alcheducation.com/wp-content/uploads/2022/10/ALCHE-Logo.png',
    country: 'South Africa', flag: '🇿🇦', city: 'Cape Town',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Entrepreneurship', 'Social Impact', 'Business'],
    description: 'Mastercard Foundation partner. African leadership college developing the next generation of African entrepreneurs and changemakers.',
    link: 'https://www.alcheducation.com',
    tags: ['Mastercard', 'Leadership', 'Entrepreneurship'],
  },
  {
    id: 4,
    name: 'Ashesi University',
    shortName: 'Ashesi',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Ashesi_University_logo.png/200px-Ashesi_University_logo.png',
    country: 'Ghana', flag: '🇬🇭', city: 'Berekuso',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Computer Science', 'Leadership', 'Business', 'Social Impact'],
    description: 'Mastercard Foundation partner. Liberal arts and engineering university focused on ethical leadership and social impact in Ghana.',
    link: 'https://www.ashesi.edu.gh',
    tags: ['Mastercard', 'Computer Science', 'Business'],
  },
  {
    id: 5,
    name: 'KNUST',
    shortName: 'KNUST',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/KNUST_logo.png/200px-KNUST_logo.png',
    country: 'Ghana', flag: '🇬🇭', city: 'Kumasi',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Engineering', 'Science', 'Technology', 'Leadership'],
    description: 'Kwame Nkrumah University of Science and Technology. Mastercard partner — premier STEM university in West Africa.',
    link: 'https://www.knust.edu.gh',
    tags: ['Mastercard', 'Engineering', 'STEM'],
  },
  {
    id: 6,
    name: 'Makerere University',
    shortName: 'Makerere',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Makerere_University_Logo.png/200px-Makerere_University_Logo.png',
    country: 'Uganda', flag: '🇺🇬', city: 'Kampala',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Medicine', 'Health Sciences', 'Social Sciences', 'Community Work'],
    description: 'Mastercard Foundation partner. One of Africa\'s oldest and most prestigious universities in Kampala, Uganda.',
    link: 'https://www.mak.ac.ug',
    tags: ['Mastercard', 'Medicine', 'Health Sciences'],
  },
  {
    id: 7,
    name: 'University of Cape Town (UCT)',
    shortName: 'UCT',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/University_of_Cape_Town_logo.svg/200px-University_of_Cape_Town_logo.svg.png',
    country: 'South Africa', flag: '🇿🇦', city: 'Cape Town',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Environmental Science', 'Climate Studies', 'Leadership'],
    description: 'Mastercard Foundation partner. Africa\'s top-ranked university — postgraduate scholarships in environmental science and climate.',
    link: 'https://www.uct.ac.za',
    tags: ['Mastercard', 'Top Ranked', 'Climate'],
  },
  {
    id: 8,
    name: 'University of Pretoria (UP)',
    shortName: 'UP',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/University_of_Pretoria_coat_of_arms.svg/200px-University_of_Pretoria_coat_of_arms.svg.png',
    country: 'South Africa', flag: '🇿🇦', city: 'Pretoria',
    region: 'africa', category: 'mastercard', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Agriculture', 'Engineering', 'Social Development'],
    description: 'Mastercard Foundation partner. Leading research university in Southern Africa with strong agriculture and engineering programs.',
    link: 'https://www.up.ac.za',
    tags: ['Mastercard', 'Agriculture', 'Engineering'],
  },
  {
    id: 9,
    name: 'University of the Western Cape',
    shortName: 'UWC',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/University_of_the_Western_Cape_logo.png/200px-University_of_the_Western_Cape_logo.png',
    country: 'South Africa', flag: '🇿🇦', city: 'Cape Town',
    region: 'africa', category: 'mastercard', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Social Sciences', 'Community Development', 'Leadership'],
    description: 'Mastercard Foundation partner. Known for social justice, community development and leadership programs.',
    link: 'https://www.uwc.ac.za',
    tags: ['Mastercard', 'Social Sciences', 'Community'],
  },
  {
    id: 10,
    name: 'University of Rwanda',
    shortName: 'UR',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/University_of_Rwanda_logo.png/200px-University_of_Rwanda_logo.png',
    country: 'Rwanda', flag: '🇷🇼', city: 'Kigali',
    region: 'africa', category: 'mastercard', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Business', 'IT', 'Social Sciences', 'Community Development'],
    description: 'Mastercard Foundation partner. Rwanda\'s flagship national university with strong IT, business and social sciences programs.',
    link: 'https://www.ur.ac.rw',
    tags: ['Mastercard', 'IT', 'Business'],
  },
  {
    id: 11,
    name: 'University of Gondar',
    shortName: 'UoG',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/University_of_Gondar_Logo.png/200px-University_of_Gondar_Logo.png',
    country: 'Ethiopia', flag: '🇪🇹', city: 'Gondar',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Medicine', 'Public Health', 'Community Support'],
    description: 'Mastercard Foundation partner. Leading health sciences and medicine university in northern Ethiopia.',
    link: 'https://www.uog.edu.et',
    tags: ['Mastercard', 'Medicine', 'Public Health'],
  },
  {
    id: 12,
    name: 'University of Abomey-Calavi',
    shortName: 'UAC',
    logo: null,
    country: 'Benin', flag: '🇧🇯', city: 'Abomey-Calavi',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Business', 'IT', 'Education', 'Social Sciences'],
    description: 'Mastercard Foundation partner. Largest university in Benin — visit website to check application status.',
    link: 'https://www.uac.bj',
    tags: ['Mastercard', 'IT', 'Business'],
  },
  {
    id: 13,
    name: 'Pan-Atlantic University',
    shortName: 'PAU',
    logo: null,
    country: 'Nigeria', flag: '🇳🇬', city: 'Lagos',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Business for Social Good'],
    description: 'Mastercard Foundation partner. Business and leadership university in Lagos, Nigeria.',
    link: 'https://www.pau.edu.ng',
    tags: ['Mastercard', 'Business', 'Leadership'],
  },
  {
    id: 14,
    name: 'USIU-Africa',
    shortName: 'USIU-A',
    logo: null,
    country: 'Kenya', flag: '🇰🇪', city: 'Nairobi',
    region: 'africa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Business', 'Social Sciences', 'Leadership'],
    description: 'United States International University-Africa. Mastercard partner — US-accredited university in Nairobi.',
    link: 'https://www.usiu.ac.ke',
    tags: ['Mastercard', 'US-Accredited', 'Business'],
  },
  {
    id: 15,
    name: 'Université Mohammed VI Polytechnique',
    shortName: 'UM6P',
    logo: null,
    country: 'Morocco', flag: '🇲🇦', city: 'Benguerir',
    region: 'africa', category: 'mastercard', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Engineering', 'Technology', 'Entrepreneurship'],
    description: 'Mastercard Foundation partner. Leading polytechnic university in North Africa focused on engineering and entrepreneurship.',
    link: 'https://www.um6p.ma',
    tags: ['Mastercard', 'Engineering', 'Technology'],
  },
  {
    id: 16,
    name: 'Université Gaston Berger (UGB)',
    shortName: 'UGB',
    logo: null,
    country: 'Senegal', flag: '🇸🇳', city: 'Saint-Louis',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Social Sciences', 'Community Development'],
    description: 'Mastercard Foundation partner. Research university in Saint-Louis, Senegal — postgraduate programs.',
    link: 'https://ugb.sn',
    tags: ['Mastercard', 'Social Sciences', 'Francophone'],
  },
  {
    id: 17,
    name: '2iE — Water & Environmental Engineering',
    shortName: '2iE',
    logo: null,
    country: 'Burkina Faso', flag: '🇧🇫', city: 'Ouagadougou',
    region: 'africa', category: 'mastercard', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Water Engineering', 'Environmental Sciences'],
    description: 'International Institute for Water and Environmental Engineering. Mastercard partner — specialist institute in West Africa.',
    link: 'https://www.2ie-edu.org',
    tags: ['Mastercard', 'Water Engineering', 'Environment'],
  },
  {
    id: 18,
    name: 'University of Global Health Equity',
    shortName: 'UGHE',
    logo: null,
    country: 'Rwanda', flag: '🇷🇼', city: 'Kigali',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Public Health', 'Health Systems', 'Social Impact'],
    description: 'Mastercard Foundation partner. Health equity-focused graduate university in Butaro, Rwanda.',
    link: 'https://ughe.org',
    tags: ['Mastercard', 'Public Health', 'Social Impact'],
  },
  {
    id: 19,
    name: 'AIMS — African Institute for Mathematical Sciences',
    shortName: 'AIMS',
    logo: null,
    country: 'Africa (Multiple)', flag: '🌍', city: 'Cape Town & Others',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Mathematics', 'Data Science', 'AI'],
    description: 'Mastercard Foundation partner. Pan-African network for mathematical sciences, data science and AI research.',
    link: 'https://nexteinstein.org',
    tags: ['Mastercard', 'Mathematics', 'Data Science', 'AI'],
  },
  {
    id: 20,
    name: 'Carnegie Mellon University Africa',
    shortName: 'CMU Africa',
    logo: null,
    country: 'Rwanda', flag: '🇷🇼', city: 'Kigali',
    region: 'africa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Software Engineering', 'AI', 'Data Science', 'Cybersecurity'],
    description: 'Mastercard Foundation partner. CMU\'s African campus in Kigali — world-class tech graduate programs.',
    link: 'https://africa.engineering.cmu.edu',
    tags: ['Mastercard', 'Software Engineering', 'AI', 'CMU'],
  },

  // ── MASTERCARD FOUNDATION — USA ─────────────────────────────
  {
    id: 21,
    name: 'Arizona State University (ASU)',
    shortName: 'ASU',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Tempe, Arizona',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Tech & Innovation for Development', 'Leadership', 'Computing'],
    description: 'Mastercard Foundation partner. Top US public university known for innovation and technology for development.',
    link: 'https://www.asu.edu',
    tags: ['Mastercard', 'Computing', 'Innovation'],
  },
  {
    id: 22,
    name: 'UC Berkeley',
    shortName: 'UC Berkeley',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Berkeley, California',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Computer Science', 'Data Science', 'Leadership'],
    description: 'Mastercard Foundation partner. World-renowned public research university in California.',
    link: 'https://www.berkeley.edu',
    tags: ['Mastercard', 'Computer Science', 'Data Science'],
  },
  {
    id: 23,
    name: 'Duke University',
    shortName: 'Duke',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Durham, North Carolina',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Global Development', 'Policy'],
    description: 'Mastercard Foundation partner. Elite research university in North Carolina.',
    link: 'https://www.duke.edu',
    tags: ['Mastercard', 'Leadership', 'Global Development'],
  },
  {
    id: 24,
    name: 'Stanford University',
    shortName: 'Stanford',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Stanford, California',
    region: 'usa', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Social Innovation', 'Leadership', 'Technology'],
    description: 'Mastercard Foundation partner. World\'s leading innovation and technology university.',
    link: 'https://www.stanford.edu',
    tags: ['Mastercard', 'Social Innovation', 'Technology'],
  },
  {
    id: 25,
    name: 'Wellesley College',
    shortName: 'Wellesley',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Wellesley, Massachusetts',
    region: 'usa', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ["Leadership", "Women's Studies", 'Social Impact'],
    description: "Mastercard Foundation partner. Elite women's liberal arts college near Boston.",
    link: 'https://www.wellesley.edu',
    tags: ['Mastercard', "Women's College", 'Leadership'],
  },

  // ── MASTERCARD FOUNDATION — CANADA ──────────────────────────
  {
    id: 26,
    name: 'McGill University',
    shortName: 'McGill',
    logo: null,
    country: 'Canada', flag: '🇨🇦', city: 'Montreal, Quebec',
    region: 'canada', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Computer Science', 'Leadership', 'Innovation'],
    description: "Mastercard Foundation partner. Canada's top-ranked university in Montreal.",
    link: 'https://www.mcgill.ca',
    tags: ['Mastercard', 'Canada', 'Computer Science'],
  },
  {
    id: 27,
    name: 'University of Toronto',
    shortName: 'U of T',
    logo: null,
    country: 'Canada', flag: '🇨🇦', city: 'Toronto, Ontario',
    region: 'canada', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['AI', 'Computing', 'Leadership'],
    description: "Mastercard Foundation partner. Canada's largest research university — strong AI and computing.",
    link: 'https://www.utoronto.ca',
    tags: ['Mastercard', 'Canada', 'AI', 'Computing'],
  },
  {
    id: 28,
    name: 'University of British Columbia (UBC)',
    shortName: 'UBC',
    logo: null,
    country: 'Canada', flag: '🇨🇦', city: 'Vancouver, BC',
    region: 'canada', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Computing', 'Engineering', 'Social Policies'],
    description: 'Mastercard Foundation partner. World-class university in Vancouver.',
    link: 'https://www.ubc.ca',
    tags: ['Mastercard', 'Canada', 'Computing', 'Engineering'],
  },

  // ── MASTERCARD FOUNDATION — UK ───────────────────────────────
  {
    id: 29,
    name: 'University of Cambridge',
    shortName: 'Cambridge',
    logo: null,
    country: 'United Kingdom', flag: '🇬🇧', city: 'Cambridge',
    region: 'uk', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Computer Science', 'Leadership', 'Innovation'],
    description: "Mastercard Foundation partner. One of the world's oldest and most prestigious universities.",
    link: 'https://www.cam.ac.uk',
    tags: ['Mastercard', 'Top Ranked', 'Computer Science'],
  },
  {
    id: 30,
    name: 'University of Oxford',
    shortName: 'Oxford',
    logo: null,
    country: 'United Kingdom', flag: '🇬🇧', city: 'Oxford',
    region: 'uk', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Public Policy', 'Social Impact'],
    description: "Mastercard Foundation partner. World's #1 ranked university.",
    link: 'https://www.ox.ac.uk',
    tags: ['Mastercard', 'Top Ranked', '#1 World'],
  },
  {
    id: 31,
    name: 'University of Edinburgh (UofE)',
    shortName: 'Edinburgh',
    logo: null,
    country: 'United Kingdom', flag: '🇬🇧', city: 'Edinburgh',
    region: 'uk', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Innovation & Development'],
    description: "Mastercard Foundation partner. Scotland's most prestigious university.",
    link: 'https://www.ed.ac.uk',
    tags: ['Mastercard', 'Scotland', 'Leadership'],
  },

  // ── MASTERCARD FOUNDATION — EUROPE & OTHER ──────────────────
  {
    id: 32,
    name: 'Sciences Po',
    shortName: 'Sciences Po',
    logo: null,
    country: 'France', flag: '🇫🇷', city: 'Paris',
    region: 'europe', category: 'mastercard', level: 'Postgraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Governance', 'Policy', 'Social Entrepreneurship'],
    description: "Mastercard Foundation partner. France's top social and political sciences university.",
    link: 'https://www.sciencespo.fr',
    tags: ['Mastercard', 'Governance', 'Policy'],
  },
  {
    id: 33,
    name: 'American University of Beirut (AUB)',
    shortName: 'AUB',
    logo: null,
    country: 'Lebanon', flag: '🇱🇧', city: 'Beirut',
    region: 'other', category: 'mastercard', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Social Change', 'Community Development'],
    description: 'Mastercard Foundation partner. Leading university in Beirut — open to African students.',
    link: 'https://www.aub.edu.lb',
    tags: ['Mastercard', 'Leadership', 'Social Change'],
  },
  {
    id: 34,
    name: 'EARTH University',
    shortName: 'EARTH',
    logo: null,
    country: 'Costa Rica', flag: '🇨🇷', city: 'San José',
    region: 'other', category: 'mastercard', level: 'Undergraduate',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Sustainable Agriculture', 'Community Empowerment'],
    description: 'Mastercard Foundation partner. Unique university focused on sustainable agriculture and community empowerment.',
    link: 'https://www.earth.ac.cr',
    tags: ['Mastercard', 'Agriculture', 'Sustainability'],
  },

  // ── FULLY FUNDED — WORK COLLEGES (USA) ──────────────────────
  {
    id: 35,
    name: 'Berea College',
    shortName: 'Berea',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Berea, Kentucky',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: '⭐ No Tuition — Work College',
    focus: ['Service Learning', 'Community Engagement', 'Leadership'],
    description: 'Every admitted student receives full tuition free. Students work on campus. Best guaranteed fully funded option for African students from poor communities.',
    link: 'https://www.berea.edu',
    tags: ['Work College', 'No Tuition', '⭐ Best Option'],
  },
  {
    id: 36,
    name: 'College of the Ozarks',
    shortName: 'C of O',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Point Lookout, Missouri',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: '⭐ No Tuition — Work College',
    focus: ['Service', 'Leadership', 'Community Development'],
    description: 'Called "Hard Work U" — students work instead of paying tuition. Highly recommended for African students who need guaranteed free education.',
    link: 'https://www.cofo.edu',
    tags: ['Work College', 'No Tuition', '⭐ Best Option'],
  },
  {
    id: 37,
    name: 'Alice Lloyd College',
    shortName: 'ALC',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Pippa Passes, Kentucky',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: 'No Tuition — Work College',
    focus: ['Leadership', 'Rural Community Support'],
    description: 'Work college in Kentucky. Free tuition for all students in exchange for campus work.',
    link: 'https://alc.edu',
    tags: ['Work College', 'No Tuition', 'Leadership'],
  },

  // ── FULLY FUNDED — IVY LEAGUE & TOP US ──────────────────────
  {
    id: 38,
    name: 'Harvard University',
    shortName: 'Harvard',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Cambridge, Massachusetts',
    region: 'usa', category: 'fullyfunded', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded / 100% Need-Based Aid',
    focus: ['Social Innovation', 'Public Policy', 'Global Development', 'Any Discipline'],
    description: 'Meets 100% of demonstrated financial need for every admitted student worldwide. No loan policy for families earning under $75,000/year.',
    link: 'https://www.harvard.edu',
    tags: ['Ivy League', 'Need-Based', 'Top Ranked'],
  },
  {
    id: 39,
    name: 'Yale University',
    shortName: 'Yale',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'New Haven, Connecticut',
    region: 'usa', category: 'fullyfunded', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded / 100% Need-Based Aid',
    focus: ['Leadership', 'Public Policy', 'Social Justice', 'Any Discipline'],
    description: 'Ivy League. Meets 100% of demonstrated financial need for all admitted students worldwide.',
    link: 'https://www.yale.edu',
    tags: ['Ivy League', 'Need-Based', 'Top Ranked'],
  },
  {
    id: 40,
    name: 'Princeton University',
    shortName: 'Princeton',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Princeton, New Jersey',
    region: 'usa', category: 'fullyfunded', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded / No-Loan Policy',
    focus: ['Leadership', 'Global Development', 'Policy', 'Any Discipline'],
    description: 'Ivy League with a no-loan policy — all financial aid given as grants, not loans. Exceptionally generous for international students.',
    link: 'https://www.princeton.edu',
    tags: ['Ivy League', 'No Loans', 'Top Ranked'],
  },
  {
    id: 41,
    name: 'Columbia University',
    shortName: 'Columbia',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'New York City, NY',
    region: 'usa', category: 'fullyfunded', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded / 100% Need-Based Aid',
    focus: ['Social Innovation', 'Leadership', 'Policy', 'Any Discipline'],
    description: 'Ivy League in New York City. Meets 100% of demonstrated financial need for all admitted international students.',
    link: 'https://www.columbia.edu',
    tags: ['Ivy League', 'Need-Based', 'NYC'],
  },
  {
    id: 42,
    name: 'MIT',
    shortName: 'MIT',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Cambridge, Massachusetts',
    region: 'usa', category: 'fullyfunded', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded / 100% Need-Based Aid',
    focus: ['Technology', 'Social Innovation', 'Engineering', 'Any Discipline'],
    description: "World's #1 tech university. Meets 100% of demonstrated financial need for all students worldwide.",
    link: 'https://web.mit.edu',
    tags: ['STEM', 'Technology', 'Need-Based', 'Top Ranked'],
  },
  {
    id: 43,
    name: 'Colorado College',
    shortName: 'CC',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Colorado Springs, CO',
    region: 'usa', category: 'fullyfunded', level: 'Undergraduate',
    funding: 'Partial Aid — Not Fully Guaranteed',
    focus: ['Liberal Arts', 'Community Engagement'],
    description: 'Liberal arts college via Common App. Partial funding available — apply alongside stronger options.',
    link: 'https://www.coloradocollege.edu',
    tags: ['Liberal Arts', 'Partial Aid', 'Community'],
  },

  // ── GLOBAL SCHOLARSHIP PROGRAMS ─────────────────────────────
  {
    id: 44,
    name: 'Mastercard Foundation Scholars Program',
    shortName: 'MFSP',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Mastercard_Foundation_logo.png/200px-Mastercard_Foundation_logo.png',
    country: 'Global', flag: '🌍', city: 'Multiple Countries',
    region: 'other', category: 'global', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded — Mastercard Foundation',
    focus: ['Leadership', 'Social Impact', 'Any Discipline — via partner universities'],
    description: 'Central hub for the Mastercard Foundation Scholars Program covering all 50+ partner universities. Start your application journey here.',
    link: 'https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/',
    tags: ['Mastercard', 'Global', 'Leadership'],
  },
  {
    id: 45,
    name: 'Fulbright Program',
    shortName: 'Fulbright',
    logo: null,
    country: 'USA', flag: '🇺🇸', city: 'Multiple US Cities',
    region: 'usa', category: 'global', level: 'Postgraduate + Research',
    funding: 'Fully Funded by US Government',
    focus: ['Any Discipline', 'Research', 'Public Policy', 'Technology'],
    description: "US government's flagship international scholarship. Full funding to study at top US universities — one of the world's most prestigious awards.",
    link: 'https://foreign.fulbrightonline.org',
    tags: ['US Government', 'Prestigious', 'Research'],
  },
  {
    id: 46,
    name: 'Chevening Scholarships',
    shortName: 'Chevening',
    logo: null,
    country: 'United Kingdom', flag: '🇬🇧', city: 'Multiple UK Cities',
    region: 'uk', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded by UK Government',
    focus: ['Leadership', 'Any Discipline'],
    description: "UK government's global scholarship for future leaders. Full funding to study a master's at any UK university — open to Africans.",
    link: 'https://www.chevening.org',
    tags: ['UK Government', 'Leadership', 'Prestigious'],
  },
  {
    id: 47,
    name: 'Commonwealth Scholarships',
    shortName: 'CSC',
    logo: null,
    country: 'UK / Commonwealth', flag: '🌍', city: 'Multiple Countries',
    region: 'uk', category: 'global', level: 'Postgraduate + PhD',
    funding: 'Fully Funded',
    focus: ['Any Discipline', 'Commonwealth Nations'],
    description: 'For students from Commonwealth countries including most African nations. Full funding to study in the UK and Commonwealth countries.',
    link: 'https://cscuk.fcdo.gov.uk',
    tags: ['Commonwealth', 'UK', 'PhD'],
  },
  {
    id: 48,
    name: 'Erasmus Mundus Joint Masters',
    shortName: 'Erasmus',
    logo: null,
    country: 'Europe', flag: '🇪🇺', city: 'Multiple EU Countries',
    region: 'europe', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded by European Union',
    focus: ['Any Discipline', 'Multiple European Countries'],
    description: 'EU-funded scholarship to study in multiple European countries. Full tuition + living allowance + travel costs paid by the EU.',
    link: 'https://ec.europa.eu/education/external-activities/erasmus-mundus_en',
    tags: ['EU Funded', 'Multiple Countries', 'Europe'],
  },
  {
    id: 49,
    name: 'DAAD Scholarships',
    shortName: 'DAAD',
    logo: null,
    country: 'Germany', flag: '🇩🇪', city: 'Multiple German Cities',
    region: 'europe', category: 'global', level: 'Undergrad & Postgrad',
    funding: 'Fully Funded by German Government',
    focus: ['Engineering', 'Science', 'Social Sciences', 'Arts'],
    description: 'German Academic Exchange Service. Full scholarship covering tuition, living costs and travel for international students in Germany.',
    link: 'https://www.daad.de/en/',
    tags: ['Germany', 'Government Funded', 'Engineering'],
  },
  {
    id: 50,
    name: 'Oxford — AfOx / Clarendon Scholarship',
    shortName: 'AfOx',
    logo: null,
    country: 'United Kingdom', flag: '🇬🇧', city: 'Oxford',
    region: 'uk', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded',
    focus: ['Any Discipline', 'AfOx specifically for African students'],
    description: 'Africa Oxford Initiative (AfOx) scholarship specifically designed for African students. Covers full fees and living costs at Oxford.',
    link: 'https://www.ox.ac.uk/clarendon',
    tags: ['Oxford', 'Africa Focus', 'Prestigious'],
  },
  {
    id: 51,
    name: 'Gates Cambridge Scholarship',
    shortName: 'Gates Cambridge',
    logo: null,
    country: 'United Kingdom', flag: '🇬🇧', city: 'Cambridge',
    region: 'uk', category: 'global', level: 'Postgraduate',
    funding: 'Fully Funded by Bill Gates Foundation',
    focus: ['Any Discipline', 'Leadership & Social Impact Focus'],
    description: 'Bill Gates-funded scholarship at Cambridge University. Full funding for outstanding international students with leadership potential.',
    link: 'https://www.gatescambridge.org',
    tags: ['Cambridge', 'Gates', 'Prestigious', 'Leadership'],
  },
];
