/* saved.js — HopeScholar | localStorage bookmarks */
'use strict';
const STORAGE_KEY='hopescholar_saved_v1';
const Saved={items:{},
init(){try{const r=localStorage.getItem(STORAGE_KEY);this.items=r?JSON.parse(r):{};}catch{this.items={};}this._updateBadge();},
has(id){return!!this.items[id];},
toggle(id,data,type){if(this.items[id]){delete this.items[id];this._updateBtn(id,false);showToast('Removed from saved');}else{this.items[id]={data,type};this._updateBtn(id,true);showToast('Saved! View in Saved tab 🔖');}this._persist();this._updateBadge();if(document.getElementById('tab-saved')?.classList.contains('active'))this.renderTab();},
remove(id,card){delete this.items[id];this._persist();this._updateBadge();if(card){card.style.transition='opacity .2s,transform .2s';card.style.opacity='0';card.style.transform='scale(.96)';setTimeout(()=>this.renderTab(),220);}else this.renderTab();},
renderTab(){const grid=$('saved-grid');const empty=$('saved-empty');const keys=Object.keys(this.items);if(!keys.length){grid.innerHTML='';showEl(empty);return;}hideEl(empty);grid.innerHTML=keys.map(id=>{const{data,type}=this.items[id];return type==='scholarship'?this._scholCard(id,data):this._uniCard(id,data);}).join('');},
_scholCard(id,s){return`<article class="schol-card" role="listitem" onclick="Scholarships.openModal(${s.id})"><div class="card-top-row"><div class="card-left"><span class="card-flag">${s.flag||'🎓'}</span><div><span class="tag tag-gold">🔖 Saved</span><p class="card-country">${escapeHtml(s.country||'')}</p></div></div><button class="bm-btn saved" onclick="event.stopPropagation();Saved.remove('${escapeHtml(id)}',this.closest('.schol-card'))" title="Remove"><svg viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2"><path d="M19 21l-7-5-7 5V5a2 2 0 012-2h10a2 2 0 012 2z"/></svg></button></div><h3 class="card-name">${escapeHtml(s.name)}</h3><p class="card-funding">${escapeHtml(s.funding||'')}</p><div class="card-footer"><span class="tag tag-gray">📚 Click to view</span><span class="card-more">View details ${ARROW_SVG}</span></div></article>`;},
_uniCard(id,u){return`<article class="uni-card" role="listitem"><div class="card-top-row"><div class="uni-icon">🏫</div><button class="bm-btn saved" onclick="Saved.remove('${escapeHtml(id)}',this.closest('.uni-card'))" title="Remove"><svg viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2"><path d="M19 21l-7-5-7 5V5a2 2 0 012-2h10a2 2 0 012 2z"/></svg></button></div><h3 class="card-name">${escapeHtml(u.name)}</h3><div class="card-footer"><span class="tag tag-green">🌍 ${escapeHtml(u.country||'')}</span>${u.url?`<a class="card-more" href="${escapeHtml(u.url)}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()">Visit Website ${ARROW_SVG}</a>`:'<span class="card-more" style="color:var(--n400)">No website</span>'}</div></article>`;},
_persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(this.items));}catch{}},
_updateBadge(){const b=$('saved-badge');if(!b)return;const c=Object.keys(this.items).length;b.textContent=c;b.style.display=c>0?'inline-block':'none';},
_updateBtn(id,saved){document.querySelectorAll('.bm-btn').forEach(b=>{if((b.getAttribute('onclick')||'').includes(id)){b.classList.toggle('saved',saved);b.querySelector('svg')?.setAttribute('fill',saved?'currentColor':'none');}});}};
